In [2]:
import numpy as np

1)

In [3]:
notes1=np.random.randint(0,21,(5,))
notes2=np.random.randint(0,21,(5,))

In [5]:
print(notes1)
print(notes2)

[ 3  1  2  1 11]
[16  6  7 14 16]


2)

In [16]:
notes= np.concatenate((notes1,notes2))

In [14]:
print(notes)

[ 3  1  2  1 11 16  6  7 14 16]


3)

In [17]:
for i in range(5):
    print("Etudiant", i, ":", notes[i], notes[i+5])

Etudiant 0 : 3 16
Etudiant 1 : 1 6
Etudiant 2 : 2 7
Etudiant 3 : 1 14
Etudiant 4 : 11 16


4)

In [27]:
notes1=np.concatenate((notes1,[np.mean(notes1)]))
notes2=np.concatenate((notes2,[np.mean(notes2)]))
print(notes1)
print(notes2)

[ 3.   1.   2.   1.  11.   3.6  3.6]
[16.   6.   7.  14.  16.  11.8 11.8]


5)

In [31]:
notes_moyenne=np.concatenate((notes1,notes2))
print("note moyenne :",notes_moyenne)

note moyenne : [ 3.   1.   2.   1.  11.   3.6  3.6 16.   6.   7.  14.  16.  11.8 11.8]


6)

In [35]:
for i in range(5):
    print("Etudiant",i,":",notes_moyenne[i],notes_moyenne[i+5])

Etudiant 0 : 3.0 3.6
Etudiant 1 : 1.0 3.6
Etudiant 2 : 2.0 16.0
Etudiant 3 : 1.0 6.0
Etudiant 4 : 11.0 7.0


In [44]:
moy_mat1 = np.mean(notes1[:-1])
moy_mat2 = np.mean(notes2[:-1])
print("Moyenne de chaque matière :", "math:",moy_mat1,"\nphysyque:", moy_mat2)


Moyenne de chaque matière : math: 3.6 
physyque: 11.799999999999999


In [45]:

moy_mat1 = np.mean(notes1[:5])
moy_mat2 = np.mean(notes2[:5])
moyennes_mat = np.array([moy_mat1, moy_mat2])
print("Moyenne de chaque matière :", moyennes_mat)

Moyenne de chaque matière : [ 3.6 11.8]
